-- Managed portfolio → public.properties
-- GENERATED by packages/db/scripts/gen-portfolio-properties-sql.mts. Re-run it
-- rather than hand-editing; the image URLs come from managed-properties.json.
--
-- Source: property_directory_Jul242026061412.pdf (33 properties),
-- photos uploaded to images/properties/<property_id>.webp — 27 of
-- 33 matched a photo; the other 6 have image = '' and will
-- render as a blank card until one is added via the CMS.
--
-- These rows go in as status 'For Sale' and appear on the public /properties
-- page. price, mls, beds, baths, garage, lot and year_built are NOT in the
-- source data and are blank/0 — fill them in on the admin Properties page.
--
-- Landlord name and phone from the directory are deliberately NOT included:
-- public.properties is served to anonymous visitors, and that is third-party
-- personal data. It stays in managed-properties.json, which is not published.
--
-- Step 1 removes the one row that was added by hand on 2026-08-06; it is
-- re-created below as p0000002 with a stable id and its photo.

begin;

delete from public.properties
 where address = '10 Bracken Ave'
   and id <> 'p0000002';

insert into public.properties (
  id, slug, image, images, price, address, area, city, province,
  beds, baths, sqft, garage, lot, year_built, mls, tag, type, status,
  description, features, coordinates
)
values
  (
    'p0000002', '10-bracken-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000002.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000002.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '10 Bracken Ave', 'East Saint Paul', 'East Saint Paul', 'Manitoba',
    0, 0, '1,676', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000040', '1221-lorette-ave',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '1221 Lorette Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,800', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000005', '179-stranmillis-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000005.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000005.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '179 Stranmillis Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,157', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000006', '1806-portage-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000006.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000006.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '1806 Portage Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '700', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000007', '1836-legion-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000007.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000007.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '1836 Legion Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '640', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000009', '187-burrows-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000009.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000009.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '187 Burrows Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '900', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000043', '190-red-pine-dr',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '190 Red Pine Dr', 'West Saint Paul', 'West Saint Paul', 'Manitoba',
    0, 0, '1,490', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000010', '1925-bannatyne-ave-w',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000010.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000010.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '1925 Bannatyne Ave W', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,157', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000011', '2002-pacific-ave-w',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000011.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000011.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '2002 Pacific Ave W', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '500', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000012', '231-dearborn-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000012.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000012.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '231 Dearborn Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '5,500', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000013', '262-collegiate-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000013.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000013.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '262 Collegiate St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '880', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000014', '281-boyd-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000014.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000014.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '281 Boyd Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,932', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000015', '30-lake-crest-rd',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000015.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000015.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '30 Lake Crest Rd', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000016', '3030-sinclair-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000016.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000016.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '3030 Sinclair St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '810', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000017', '355-woodlawn-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000017.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000017.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '355 Woodlawn St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000019', '382-queen-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000019.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000019.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '382 Queen St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000020', '425-salter-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000020.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000020.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '425 Salter St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,000', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000021', '427-pritchard-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000021.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000021.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '427 Pritchard Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '970', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000022', '47-bayne-crescent',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000022.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000022.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '47 Bayne Crescent', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,309', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000023', '525-sherbrook-st',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000023.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000023.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '525 Sherbrook St', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,000', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000024', '57-berkshire-bay',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000024.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000024.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '57 Berkshire Bay', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,035', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000025', '61-imperial-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000025.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000025.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '61 Imperial Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,040', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000026', '617-elgin-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000026.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000026.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '617 Elgin Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,550', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000027', '626-garwood-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000027.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000027.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '626 Garwood Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '700', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000028', '628-garwood-ave',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '628 Garwood Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '700', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000044', '633-st-mary-s-rd',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '633 St Mary''s Rd', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,800', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000041', '703-prince-rupert-avenue',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '703 Prince Rupert Avenue', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,250', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000030', '8-werrell-crescent',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000030.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000030.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '8 Werrell Crescent', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '880', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000031', '805-hector-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000031.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000031.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '805 Hector Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,284', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000032', '869-hector-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000032.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000032.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '869 Hector Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '2,232', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000033', '88-st-mary-s-rd',
    '',
    '{}',
    '',                                  -- price: not in source (managed, not listed)
    '88 St Mary''s Rd', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,002', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000034', '904-college-ave',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000034.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000034.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '904 College Ave', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,800', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  ),
  (
    'p0000035', '98-mt-auburn-bay',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000035.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/properties/p0000035.webp'],
    '',                                  -- price: not in source (managed, not listed)
    '98 Mt Auburn Bay', 'Winnipeg', 'Winnipeg', 'Manitoba',
    0, 0, '1,459', 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  )
on conflict (id) do update set
  image      = excluded.image,
  images     = excluded.images,
  address    = excluded.address,
  area       = excluded.area,
  city       = excluded.city,
  province   = excluded.province,
  sqft       = excluded.sqft,
  updated_at = now();
-- price/mls/beds/baths/garage/lot/year_built/description/features are left out
-- of the DO UPDATE list on purpose, so re-running this never wipes values that
-- were filled in through the CMS.

commit;
