-- Real vacant units — GENERATED by apps/admin/scripts/seed-rental-images.mts.
-- Re-run that script rather than hand-editing the image URLs.
--
-- Source: units marked VACANT in 'Pictures/Sqft.xlsx', cross-referenced with
-- property_directory_Jul242026061412.pdf. Photos come from the matched
-- 'Properties DB Export/images/', re-encoded to WebP by the same optimize step
-- the CMS uploader uses, and stored under images/rentals/ in Supabase Storage.
--
-- rent, beds, baths and area are NOT in the source data (no active lease to
-- read them from) and are blank/0 below on purpose. Fill them in on the admin
-- Rentals page before publishing, or edit here and re-run — this is an upsert.

insert into public.rentals (id, image, images, rent, address, area, beds, baths, sqft, category, status)
values
  (
    'r-525-sherbrook-a',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-525-sherbrook-a.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-525-sherbrook-a.webp'],
    '',                          -- TODO: rent (not in source data)
    '525 Sherbrook St, Unit A',
    'Winnipeg',                  -- TODO: neighbourhood, e.g. 'West Broadway'
    0, 0,                        -- TODO: beds, baths (not in source data)
    '',                          -- property total is 2,000 sqft / 2 units
    'Residential',
    'Available'
  ),
  (
    'r-61-imperial',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-61-imperial.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-61-imperial.webp'],
    '',                          -- TODO: rent (not in source data)
    '61 Imperial Ave',
    'Winnipeg',                  -- TODO: neighbourhood, e.g. 'West Broadway'
    0, 0,                        -- TODO: beds, baths (not in source data)
    '1,040',                     -- whole property (single unit), from the property directory
    'Residential',
    'Available'
  ),
  (
    'r-869-hector-a',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-869-hector-a.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-869-hector-a.webp'],
    '',                          -- TODO: rent (not in source data)
    '869 Hector Ave, Unit A',
    'Winnipeg',                  -- TODO: neighbourhood, e.g. 'West Broadway'
    0, 0,                        -- TODO: beds, baths (not in source data)
    '',                          -- property total is 2,232 sqft / 2 units
    'Residential',
    'Available'
  ),
  (
    'r-904-college-a',
    'https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-904-college-a.webp',
    array['https://cfojarfvdthazqoltrlt.supabase.co/storage/v1/object/public/images/rentals/r-904-college-a.webp'],
    '',                          -- TODO: rent (not in source data)
    '904 College Ave, Unit A',
    'Winnipeg',                  -- TODO: neighbourhood, e.g. 'West Broadway'
    0, 0,                        -- TODO: beds, baths (not in source data)
    '',                          -- property total is 1,800 sqft / 2 units
    'Residential',
    'Available'
  )
on conflict (id) do update set
  image      = excluded.image,
  images     = excluded.images,
  address    = excluded.address,
  sqft       = excluded.sqft,
  category   = excluded.category,
  status     = excluded.status,
  updated_at = now();
-- Note: rent/area/beds/baths are intentionally left out of the DO UPDATE list,
-- so re-running this after someone fills them in on the Rentals page will not
-- wipe their work.
