/**
 * Generates `packages/db/portfolio-properties.seed.sql` from
 * `packages/db/managed-properties.json` (itself produced by
 * apps/admin/scripts/seed-rental-images.mts --properties).
 *
 * Run from packages/db:  npx tsx scripts/gen-portfolio-properties-sql.mts
 *
 * Pure file transform — no network, no credentials. Re-run it after the
 * manifest changes rather than hand-editing the SQL.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const IN = join(here, "..", "managed-properties.json");
const OUT = join(here, "..", "portfolio-properties.seed.sql");

interface Entry {
  property_id: string;
  address: string;
  city: string;
  province: string;
  units: number;
  sqft: number | null;
  published: boolean;
  image: string | null;
}

const entries = JSON.parse(readFileSync(IN, "utf-8")) as Entry[];

/** Postgres single-quote escaping. */
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const PROVINCE: Record<string, string> = { MB: "Manitoba" };

// slug is NOT NULL UNIQUE — a collision would abort the whole insert.
const slugs = new Map<string, string>();
for (const e of entries) {
  const slug = slugify(e.address);
  const clash = slugs.get(slug);
  if (clash) throw new Error(`slug collision: ${clash} and ${e.property_id} both → '${slug}'`);
  slugs.set(slug, e.property_id);
}

const withPhoto = entries.filter((e) => e.image).length;

const rows = entries
  .map((e) => {
    const img = e.image ?? "";
    const images = e.image ? `array[${q(e.image)}]` : "'{}'";
    const sqft = e.sqft ? e.sqft.toLocaleString("en-CA") : "";
    return `  (
    ${q(e.property_id)}, ${q(slugify(e.address))},
    ${q(img)},
    ${images},
    '',                                  -- price: not in source (managed, not listed)
    ${q(e.address)}, ${q(e.city)}, ${q(e.city)}, ${q(PROVINCE[e.province] ?? e.province)},
    0, 0, ${q(sqft)}, 0, '', 0,          -- beds, baths, sqft, garage, lot, year_built
    '',                                  -- mls: not in source
    '', 'Residential', 'For Sale',
    '',                                  -- description
    '{}', '{"lng":0,"lat":0}'
  )`;
  })
  .join(",\n");

const sql = `-- Managed portfolio → public.properties
-- GENERATED by packages/db/scripts/gen-portfolio-properties-sql.mts. Re-run it
-- rather than hand-editing; the image URLs come from managed-properties.json.
--
-- Source: property_directory_Jul242026061412.pdf (${entries.length} properties),
-- photos uploaded to images/properties/<property_id>.webp — ${withPhoto} of
-- ${entries.length} matched a photo; the other ${entries.length - withPhoto} have image = '' and will
-- render as a blank card until one is added via the CMS.
--
-- These rows go in as status 'For Sale' and appear on the public /properties
-- page. price, mls, beds, baths, garage, lot and year_built are NOT in the
-- source data and are blank/0 — fill them in on the admin Properties page.
--
-- Landlord name and phone from the directory are deliberately NOT included:
-- public.properties is served to anonymous visitors, and that is third-party
-- personal data. It stays in managed-properties.json, which is not published.
--
-- Step 1 removes the one row that was added by hand on 2026-08-06; it is
-- re-created below as ${slugs.get("10-bracken-ave") ?? "p0000002"} with a stable id and its photo.

begin;

delete from public.properties
 where address = '10 Bracken Ave'
   and id <> 'p0000002';

insert into public.properties (
  id, slug, image, images, price, address, area, city, province,
  beds, baths, sqft, garage, lot, year_built, mls, tag, type, status,
  description, features, coordinates
)
values
${rows}
on conflict (id) do update set
  image      = excluded.image,
  images     = excluded.images,
  address    = excluded.address,
  area       = excluded.area,
  city       = excluded.city,
  province   = excluded.province,
  sqft       = excluded.sqft,
  updated_at = now();
-- price/mls/beds/baths/garage/lot/year_built/description/features are left out
-- of the DO UPDATE list on purpose, so re-running this never wipes values that
-- were filled in through the CMS.

commit;
`;

writeFileSync(OUT, sql, "utf-8");
console.log(`${entries.length} properties (${withPhoto} with a photo, ${entries.length - withPhoto} without)`);
console.log(`Wrote ${OUT}`);
